### ISSUE TITLE
[Bug] Installing an extension is stuck in an "installing loop"

### ISSUE THREAD

**Issue by dothackjhe** [AriaMoradi/Tachidesk#263] opened 2021-12-01 04:43 UTC
## Device information
- Tachidesk version: 0.6.0
- Server Operating System: Windows 10 x64
- Server Desktop Environment: N/A
- Server JVM version: Version 8 Update 311
- Client Operating System: Windows 10 x64
- Client Web Browser: Microsoft Edge

## Steps to reproduce
1. Navigate to Extensions
2. Pick an Extension of choice and choose to install

### Expected behavior
A successful install.

### Actual behavior
Instead of a successful install, the process seems never-ending.

**Comment by AriaMoradi** [comment] 2021-12-01 08:19
Duplicate of #237

**Closed as completed by AriaMoradi** 2021-12-01 08:19 UTC
Labels: bug

**Comment by dothackjhe** [comment] 2021-12-01 08:22
Found the solution to the problem: instead of running the provided .jar file, use one of the .bat files instead.
