### ISSUE TITLE
[Feature Request] Download multiple chapters 

### ISSUE THREAD

**Issue by assome1** [AriaMoradi/Tachidesk#433] opened 2022-10-30 12:13 UTC
I want to download multiple chapters or even the whole manga like in the phone app.
Also, is it possible for pages to be saved in .png format?

**Comment by AriaMoradi** [comment] 2022-10-30 13:23
duplicate of #181

**Comment by AriaMoradi** [comment] 2022-10-30 13:23
And no saving in png format, use a convector program like imagemagick

**Closed as completed by AriaMoradi** 2022-10-30 13:23 UTC
Labels: enhancement
