### ISSUE TITLE
[Bug] Extension not installed

### ISSUE THREAD

**Issue by metalme** [AriaMoradi/Tachidesk#471] opened 2022-12-27 03:02 UTC
Device information
- Tachidesk version: (Tachidesk-Server-v0.6.6-r1159-windows-x64)
- Server Operating System: (Windows 10 Pro Mini OS 10 Pro 2022)
- Server Desktop Environment: N/A
![4](https://user-images.githubusercontent.com/121469140/209604225-37f699d6-6a8c-46b4-83a0-9288390e022a.png)
![3](https://user-images.githubusercontent.com/121469140/209604228-850c376d-62bd-483b-a25d-9d51b8cda9a2.png)
![2](https://user-images.githubusercontent.com/121469140/209604230-8f96f141-64bc-4025-84a4-cc5568ee8ae8.png)
![1](https://user-images.githubusercontent.com/121469140/209604237-2477f91c-ebd9-4488-b9a4-195ee6d5c0ba.png)
![5](https://user-images.githubusercontent.com/121469140/209604338-5ae6715a-9cb2-4988-9e4a-f5c8464e6845.png)

- Server JVM version: bundled with win32 or (Java 8 Update 51 -351)
- Client Operating System: Windows 10 Pro Mini OS 10 Pro 2022
- Client Web Browser: Google Chrome 108.0.5359.125--firefox 108.0.1--microsoft Edge 108.01462.54

## Steps to play
1. First Step--Run Tachidesk Server
2. Second Step--Open tachidesk in Chrome

### Expected behavior
Clicking on install extension should install extension, the option to uninstall the extension will appear and the extension will appear in source to access its library

### Actual behavior
When clicking on install extension the button remains bugged, when you continue downloading and uploading again the install appears again, it should show uninstall

## Other details
I go to the root folder where the downloaded file should be to run it and install the extension on my own, and it appears (Error: invalid or corrupt jar file) followed by the path where the file is
I tried several extensions and it was always the same
I also tried several browsers
local source is working normally

**Comment by Syer10** [comment] 2022-12-27 04:29
How are you running Tachidesk-Server? You either need to use the launcher files(.bat files on Windows) or use a non-oracle java like [Temurin](https://adoptium.net/)

**Comment by metalme** [comment] 2022-12-28 02:09
directly from the folder
![image](https://user-images.githubusercontent.com/121469140/209744557-806e2b43-bde7-4447-9331-7af5b33201b0.png)

I am downloading to test temurin..I already report how it goes

**Comment by Syer10** [comment] 2022-12-28 02:22
Duplicate of https://github.com/Suwayomi/Tachidesk-Server/issues/237 👍

**Closed as completed by Syer10** 2022-12-28 02:22 UTC
Labels: bug

**Comment by metalme** [comment] 2022-12-28 03:16
Done Brother Download, Install and Launch, It works now yes
the installation of the extension, the sources appear, s is added and updated to the library thank you very much brother
