### ISSUE TITLE
[Bug] Manga with long lists of authors fail with "Could not load manga"

### ISSUE THREAD

**Issue by ceridwen** [AriaMoradi/Tachidesk#1204] opened 2024-12-16 09:03 UTC
## Device information
- Suwayomi-Server version: v1.1.1
- Server Operating System: Ubuntu 22.04
- Server Desktop Environment: Gnome 42.9
- Server JVM version: OpenJDK 64-Bit Server VM (build 11.0.25+9-post-Ubuntu-1ubuntu122.04, mixed mode, sharing)
- Client Operating System: same
- Client Web Browser: Firefox 133.0

## Steps to reproduce

1. Try to load a manga with an author list longer than 512 characters (many anthologies for instance).

### Expected behavior

The manga loads normally.

### Actual behavior

See an error like the author list followed by "can't be stored to database column because exceeds length 512."

**Comment by Robonau** [comment] 2024-12-16 09:56
description had a similar issue before #54
was fixed by truncating.

**Comment by Nitrousoxide** [comment] 2024-12-21 17:07
I see there was already an issue now after I opened mine, so I'm closing mine and will give a more detailed run down of how to replicate it.
Device information

    Suwayomi-Server version: v1.1.1
    Server Operating System: Docker image (host server is running on Bookworm however)
    Server Desktop Environment: N/A
    Server JVM version: Whatever it is for ghcr.io/suwayomi/tachidesk:stable
    Client Operating System: Haven't checked the dockerfile, but whatever the base distro is for ghcr.io/suwayomi/tachidesk:stable
    Client Web Browser: Firefox 11.21.0

Steps to reproduce

    Setup extension sources
    Install mangadex source
    Search for manga with very long series or artist name (example: [Link](https://mangadex.org/title/027df837-7a15-4893-9dc3-e2ae11b94717/onii-chan-is-done-for-official-anthology-comic))
    Get error:
![image](https://github.com/user-attachments/assets/e89a4aed-5fd4-47db-a5cc-6f08ecd615c6)

Expected behavior

Excessive name lengths should be truncated or otherwise handled gracefully rather than erroring out.
Actual behavior

App throws error and is unable to load series chapter list

**Comment by schroda** [comment] 2024-12-21 17:14
this has already been fixed (0adbea3a43c021c072e276b0bfe867527006a5bd)

**Closed as completed by schroda** 2024-12-21 17:14 UTC
Labels: bug

**Comment by Nitrousoxide** [comment] 2024-12-21 17:25
Ah, so the fix is in the repo, but not the 1.1.1 build then?  I don't think a new release has been published since that commit.

I guess we'll just have to wait for the next release.

**Comment by Syer10** [comment] 2024-12-21 17:50
Its available in the Preview version which you can find in the ReadMe
