### ISSUE TITLE
[Feature Request] Sorting by last readed asc/desc

### ISSUE THREAD

**Issue by Zaryu** [AriaMoradi/Tachidesk#390] opened 2022-08-14 14:55 UTC
A sorting option to sort by last readed asc/desc whould be awesome, to keep track of your last readed mangas, so you can easily continue reading, without scrolling or searching for your last readed mangas.

Running tachidesk-server docker dev build & tachidesk-sorayomi(android)

**Comment by Syer10** [comment] 2023-08-05 03:09
Duplicate of #307

**Closed as not planned by Syer10** 2023-08-05 03:09 UTC
Labels: enhancement
