### ISSUE TITLE
Windows installer issue. 

### ISSUE THREAD

**Issue by Feralnet** [AriaMoradi/Tachidesk#399] opened 2022-09-01 06:08 UTC
The JRE folder's files are not in the folder specified in the installpath.  It goes
.\Tachidesk-Server\jre\jdk8u292-b10-jre
instead of the files being in 
.\Tachidesk-Server\jre\

Moved the files from the former to the latter and the program works again.

**Comment by AriaMoradi** [comment] 2022-09-01 11:48
The issue is fixed in preview releases

**Closed as completed by AriaMoradi** 2022-09-01 11:48 UTC
