### ISSUE TITLE
[Feature Request] The ability to scroll using spacebar rather than jumping on next page.

### ISSUE THREAD

**Issue by syedaliasad649** [AriaMoradi/Tachidesk#208] opened 2021-09-27 09:36 UTC
## What feature should be added to Tachidesk?
*same as title*

##  Why/Project's Benefit/Existing Problem
Many manga have long pages, some which can't be displayed in one page and require scroll. 
The default way to scroll in webpages is to use spacebar which here, makes you jump to the next page. 
Its a minor inconvenience but I think it effects enough people to be brought up here.

**Comment by Robonau** [comment] 2022-06-19 16:18
wrong repo
dupe of Suwayomi/Tachidesk-WebUI#162

**Closed as completed** 2022-06-19 16:42 UTC
Labels: enhancement
