### ISSUE TITLE
[Bug] Local source Shows every chapter twice

### ISSUE THREAD

**Issue by ff2400t** [AriaMoradi/Tachidesk#265] opened 2021-12-01 13:38 UTC
---

## Device information
- Tachidesk version: v0.5.4-r1045-windows-x64
- Server Operating System: Windows 10 19043.1319
- Server Desktop Environment: N/A
- Server JVM version: OpenJDK 8.0.302+8
- Client Operating System: Same as the server
- Client Web Browser: Google Chrome 96 and Firefox 95

## Steps to reproduce
1. Open any Manga from local source
2. All the chapters are listed twice

### Expected behavior
The number of chapter should be the same as the number of folder in the local/mangaName folder

### Actual behavior
All the chapters are listed twice by the API when the manga onlineFetch query parameter is set to false

## Other details
This is server issue as i have deleted the Database file and It still gives the same result. This probably happens when the manga chapters are fetched for the first time. The server might be entering all the chapters from the local source twice in the database.
When onlineFetch is true it gives the correct number of chapters. 
In web UI at least the chapter list is fetched three times, first time with onlineFetch=false, then with onlineFetch set to true which gives the correct chapters and then as onlineFetch set to False which uses the incorrect Chapter Data.

**Comment by AriaMoradi** [comment] 2021-12-01 19:24
I couldn't reproduce this with v0.6.0 maybe something we fixed and forgot about?

**Comment by AriaMoradi** [comment] 2022-02-19 02:14
fixed in #294

**Closed as completed by AriaMoradi** 2022-02-19 02:14 UTC
Labels: bug
