### ISSUE TITLE
[Feature Request] Flatpak for Linux

### ISSUE THREAD

**Issue by samarthkharbanda** [AriaMoradi/Tachidesk#653] opened 2023-08-11 15:40 UTC
Can you please create and maintain a Flatpak for tachidesk it is much easier to use and can be used across various destros which are not debian based.

I.e., Fedora etc

**Comment by Syer10** [comment] 2023-08-21 01:09
Duplicate of #489

**Closed as not planned by Syer10** 2023-08-21 01:09 UTC
