### ISSUE TITLE
[Feature Request] Fit images to height in Single Page reader mode

### ISSUE THREAD

**Issue by jackle3** [AriaMoradi/Tachidesk#291] opened 2022-01-27 04:11 UTC
## What feature should be added to Tachidesk?
The ability to make images fit to the height of the window in single page reader mode. 

##  Why/Project's Benefit/Existing Problem
Currently, the single-page reader mode is much like webtoon mode, where the image is stretched to fit the width (or shown in its original size, I'm not too sure). This is extremely unuseful for those who want to read in single-page mode using the keyboard (ie. arrow keys) to navigate through pages, since they would have to scroll down to see the rest of the page/image. Here's a gif of what I'm talking about: https://gyazo.com/811faccbfff489e8bc83ec07f26e71a3

**Comment by Syer10** [comment] 2022-01-27 04:12
Duplicate of https://github.com/Suwayomi/Tachidesk-WebUI/issues/13

**Closed as completed by Syer10** 2022-01-27 04:12 UTC
Labels: enhancement
