### ISSUE TITLE
[Feature Request] download detector 

### ISSUE THREAD

**Issue by xdeiimoss** [AriaMoradi/Tachidesk#946] opened 2024-05-09 22:48 UTC
## What feature should be added to Suwayomi?
In Mihon, there's an option to invalidate downloads index to force check downloaded chapters, in case you downloaded stuff in other forks.

##  Why/Project's Benefit/Existing Problem
I'd say it would be a good option for Suwayomi in case the database gets corrupted or when creating a new database. I personally had to create another one because it's size was getting out of hand.

**Comment by Robonau** [comment] 2024-05-09 23:16
duplicate of #732

**Closed as not planned** 2024-05-10 00:18 UTC
Labels: enhancement
