### ISSUE TITLE
[Feature Request] Download Button Menu

### ISSUE THREAD

**Issue by marmattheo** [AriaMoradi/Tachidesk#364] opened 2022-06-01 21:01 UTC
## What feature should be added to Tachidesk?
When opening a specific manga, a download button should appear with a dropdown menu; for Tachiyomi's reference, the elements that are included inside the download menu are (Next Chapter, Next 5 Chapters, Next 10 Chapters, Custom, Unread, All). The program will download in accordance with the item selected by the user.

##  Why/Project's Benefit/Existing Problem
This will eliminate the time-consuming process of downloading a large number of chapters when learning about a new manga. If this function is implemented, users with unstable internet connection will be able to enjoy more reading offline because of this hassle-free solution.

**Comment by Robonau** [comment] 2022-06-01 21:08
blocked by #181 server side
dupe of Suwayomi/Tachidesk-WebUI#17

**Closed as completed** 2022-06-01 21:17 UTC
Labels: enhancement
