### ISSUE TITLE
[Bug] certain extensions do not install

### ISSUE THREAD

**Issue by gitrosers** [AriaMoradi/Tachidesk#315] opened 2022-03-18 19:02 UTC
## Device information
- Tachidesk version: (latest stable docker build)
Server version
v0.6.2
Build time
Fri, 04 Mar 2022 15:50:55 GMT

## Steps to reproduce
1. try installing newtoki jmana and toonkor extensions.
2. these extensions appear as "installing" but then nothing happens.
3. the relevant jar files are downloaded but they appear as not installed on the webui.
4. try installing apk downloaded off tachiyomi within the webui menu also does not work.

### Expected behavior
extensions to work as other extensions (e.g., naver webtoon).

### Actual behavior
the said extensions do not install and when the user interface is refreshed, showing as not installed (.jar files are still saved in the extensions directory).

**Comment by Syer10** [comment] 2022-03-18 19:05
Duplicate of https://github.com/Suwayomi/Tachidesk-Server/issues/237

**Comment by gitrosers** [comment] 2022-03-18 19:09
> 

I do not think this is the same issue.  I can install other extensions fine but just those three.  They do not show up on the sources either upon installing, however.  Also, the issue comes from the docker build so I do not see how this is caused by having a bad java build.

**Comment by Syer10** [comment] 2022-03-18 19:11
Weird, does it output any logs in the log textfile?

**Comment by Robonau** [comment] 2022-03-18 19:11
ye, i told him in discord already (im also using docker)
(i got no logs when the issue happened)

**Comment by Robonau** [comment] 2022-03-18 19:14
imma try a fresh setup

**Comment by gitrosers** [comment] 2022-03-18 19:15
I don't think this helps much but here is the log when I click on the install button.

"15:14:35.498 [DefaultDispatcher-worker-1] [39mDEBUG[0;39m suwayomi.tachidesk.manga.impl.extension.Extension - Installing eu.kanade.tachiyomi.extension.ko.newtoki
Mar 18, 2022 3:14:35 PM okhttp3.internal.platform.Platform log
INFO: --> GET https://raw.githubusercontent.com/tachiyomiorg/tachiyomi-extensions/repo//apk/tachiyomi-ko.newtoki-v1.2.22.apk
Mar 18, 2022 3:14:35 PM okhttp3.internal.platform.Platform log
INFO: <-- 200 https://raw.githubusercontent.com/tachiyomiorg/tachiyomi-extensions/repo/apk/tachiyomi-ko.newtoki-v1.2.22.apk (18ms, 104317-byte body)
15:14:35.559 [DefaultDispatcher-worker-1] [39mDEBUG[0;39m suwayomi.tachidesk.manga.impl.extension.Extension - Main class for extension is eu.kanade.tachiyomi.extension.ko.newtoki.NewTokiFactory
15:14:35.636 [DefaultDispatcher-worker-1] [39mDEBUG[0;39m suwayomi.tachidesk.manga.impl.util.PackageTools - loading jar with path: /home/suwayomi/.local/share/Tachidesk/extensions/tachiyomi-ko.newtoki-v1.2.22.jar
15:14:35.655 [DefaultDispatcher-worker-1] [39mDEBUG[0;39m suwayomi.tachidesk.manga.impl.extension.ExtensionsList - Getting extensions list from the internet
Mar 18, 2022 3:14:35 PM okhttp3.internal.platform.Platform log
INFO: --> GET https://raw.githubusercontent.com/tachiyomiorg/tachiyomi-extensions/repo//index.min.json
Mar 18, 2022 3:14:35 PM okhttp3.internal.platform.Platform log
INFO: <-- 200 https://raw.githubusercontent.com/tachiyomiorg/tachiyomi-extensions/repo/index.min.json (22ms, unknown-length body)"

**Comment by AriaMoradi** [comment] 2022-03-18 21:52
Normal install logs look like
```
INFO: --> GET https://raw.githubusercontent.com/tachiyomiorg/tachiyomi-extensions/repo/icon/tachiyomi-ru.newbie-v1.2.8.png
Mar 19, 2022 1:19:18 AM okhttp3.internal.platform.Platform log
INFO: <-- 200 https://raw.githubusercontent.com/tachiyomiorg/tachiyomi-extensions/repo/icon/tachiyomi-ru.newbie-v1.2.8.png (302ms, 5032-byte body)
01:19:21.811 [DefaultDispatcher-worker-5] DEBUG suwayomi.tachidesk.manga.impl.extension.Extension - Installing eu.kanade.tachiyomi.extension.ru.newbie
Mar 19, 2022 1:19:21 AM okhttp3.internal.platform.Platform log
INFO: --> GET https://raw.githubusercontent.com/tachiyomiorg/tachiyomi-extensions/repo//apk/tachiyomi-ru.newbie-v1.2.8.apk
Mar 19, 2022 1:19:22 AM okhttp3.internal.platform.Platform log
INFO: <-- 200 https://raw.githubusercontent.com/tachiyomiorg/tachiyomi-extensions/repo/apk/tachiyomi-ru.newbie-v1.2.8.apk (753ms, 74954-byte body)
01:19:22.635 [DefaultDispatcher-worker-5] DEBUG suwayomi.tachidesk.manga.impl.extension.Extension - Main class for extension is eu.kanade.tachiyomi.extension.ru.newbie.Newbie
01:19:22.825 [DefaultDispatcher-worker-5] DEBUG suwayomi.tachidesk.manga.impl.util.PackageTools - loading jar with path: /home/armor/.local/share/Tachidesk/extensions/tachiyomi-ru.newbie-v1.2.8.jar
01:19:22.844 [DefaultDispatcher-worker-5] DEBUG suwayomi.tachidesk.manga.impl.extension.Extension - Installed source NewManga(Newbie) (ru) with id:8033757373676218584
```

NewToki logs are
```
01:21:40.851 [DefaultDispatcher-worker-5] DEBUG suwayomi.tachidesk.manga.impl.extension.Extension - Installing eu.kanade.tachiyomi.extension.ko.newtoki
Mar 19, 2022 1:21:40 AM okhttp3.internal.platform.Platform log
INFO: --> GET https://raw.githubusercontent.com/tachiyomiorg/tachiyomi-extensions/repo//apk/tachiyomi-ko.newtoki-v1.2.22.apk
Mar 19, 2022 1:21:41 AM okhttp3.internal.platform.Platform log
INFO: <-- 200 https://raw.githubusercontent.com/tachiyomiorg/tachiyomi-extensions/repo/apk/tachiyomi-ko.newtoki-v1.2.22.apk (372ms, 104317-byte body)
01:21:41.365 [DefaultDispatcher-worker-5] DEBUG suwayomi.tachidesk.manga.impl.extension.Extension - Main class for extension is eu.kanade.tachiyomi.extension.ko.newtoki.NewTokiFactory
01:21:41.508 [DefaultDispatcher-worker-5] DEBUG suwayomi.tachidesk.manga.impl.util.PackageTools - loading jar with path: /home/armor/.local/share/Tachidesk/extensions/tachiyomi-ko.newtoki-v1.2.22.jar
```

**Comment by AriaMoradi** [comment] 2022-03-18 22:24
```
java.lang.NoClassDefFoundError: eu/kanade/tachiyomi/BuildConfig
    at eu.kanade.tachiyomi.extension.ko.newtoki.NewToki.<clinit>(Unknown Source)
    at eu.kanade.tachiyomi.extension.ko.newtoki.NewTokiFactory.createSources(Unknown Source)
    at suwayomi.tachidesk.manga.impl.extension.Extension.installAPK(Extension.kt:148)
    at suwayomi.tachidesk.manga.impl.extension.Extension$installAPK$1.invokeSuspend(Extension.kt)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.ClassNotFoundException: eu.kanade.tachiyomi.BuildConfig
    at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 12 more
```

and `NoClassDefFoundError` is an `Error` not an `Exception` so it doesn't get caught

**Closed as completed** 2022-03-18 23:06 UTC
Labels: bug
