### ISSUE TITLE
[Bug] Jinmantiantang after click chapter when loading no image is load

### ISSUE THREAD

**Issue by ericvlog** [AriaMoradi/Tachidesk#355] opened 2022-05-08 03:45 UTC
---

## Device information
- v0.6.2-r1083 Docker-Compose
- Server Operating System: Debian 11
- Server Desktop Environment: N/A
- Server JVM version: docker
- Client Operating System: v0.6.2-r1083 Docker-Compose , tachiyomi
- Client Web Browser: chrome Version 100.0.4896.88 (Official Build) (64-bit)

## Steps to reproduce
1. extension install Jinmantiantang 
2. go to source and browse manga.
3. when click chapter images cannot loading.

### Expected behavior
the manga should start after click on the chapter

### Actual behavior
after loading it just back blackground.

## Other details
Try other extension with no problem, i also have try Jinmantiantang  on tachiyomi is working well, but from tachiyomi source tachidesk Jinmantiantang  also cannot, it say "The image couldn't be loaded".

**Comment by Robonau** [comment] 2022-05-15 16:29
i can't really understand the broken english, so il ask for confirmation:

does the Jinmantiantang chapter work on tachiyomi?
if it does not work then it is a tachiyomi issue, not a tachidesk issue

**Comment by ericvlog** [comment] 2022-05-15 17:15
> i can't really understand the broken english, so il ask for confirmation:
> 
> does the Jinmantiantang chapter work on tachiyomi? if it does not work then it is a tachiyomi issue, not a tachidesk issue

tachiyomi can work, but tachidesk cannot.

**Comment by AriaMoradi** [comment] 2022-12-04 10:18
duplicate of #444

**Closed as completed by AriaMoradi** 2022-12-04 10:18 UTC
Labels: bug
