### ISSUE TITLE
[Bug] Chapters that I downloaded have their pages shuffled

### ISSUE THREAD

**Issue by PieceKlowne** [AriaMoradi/Tachidesk#528] opened 2023-03-23 09:59 UTC
## Device information
- Tachidesk version: v0.7.-1.0-r1197-macOS-x64
- Server Operating System: macOS Big Sur Version 11.4 (20F71)
- Server Desktop Environment: N/A
- Server JVM version: Java 8 Update 361 (build 1.8.0_361-b09)
- Client Operating System: macOS Big Sur Version 11.4 (20F71)
- Client Web Browser: Version 111.0.5563.110 (Official Build) (x86_64)

## Steps to reproduce
1. First Step: Download all chapters from a Manga.

### Expected behavior
All chapters are downloaded and the pages are in order.

### Actual behavior
All chapters are downloaded and the pages are shuffled and not in order.

## Other details
This happened on multiple Mangas which I downloaded all of their chapters and are on different extensions/sources.

**Comment by koskit** [comment] 2023-04-01 22:44
I second this. It only happens when a chapter is downloaded. In case it is read online, the correct order is shown, but after download, I found some chapters had their first page on page seven (opened the image in a separate tab and saw it). 
Tried with asura scans and flame scans.

And once downloaded, even if I delete them, the "wrong" order still persists.

**Comment by koskit** [comment] 2023-04-01 22:48
One more thing, I saw on the download folder inside tachidesk files, that the image files had correct naming on their order.

001.jpg was the actual 1st image, 002 the second etc.

It seems the web ui messes it up.

**Comment by Carpe-Diem-Postero** [comment] 2023-04-16 17:22
> I second this. It only happens when a chapter is downloaded. In case it is read online, the correct order is shown, but after download, I found some chapters had their first page on page seven (opened the image in a separate tab and saw it). Tried with asura scans and flame scans.
> 
> And once downloaded, even if I delete them, the "wrong" order still persists.

I can confirm this exact behavior

If you delete the downloaded images, clear the cache, and reload the chapter from the online source, this fixes the problem, but the moment you download the chapter again, the bug reappears.

**Comment by linoth** [comment] 2023-05-18 00:51
Apologies, I'm not really a good coder, or good with git/github, but encountered this and poked it a little because it annoyed me.  Wanted to share findings in case it made tracking down the bug easier.

Running the stable docker image (appears to be 0.7.0 build @ Feb 12 2023 19:50:49 GMT) on Ubuntu 22.04.2 and docker 20.10.21 w/ go1.18.1, drive formatted in ext4.

Downloaded an arbitrary chapter from MangaSee, and browsed to it.
Opened manga in Tachidesk and pages were out of order (29 5 3 25 22...)
Browsed to the files in the tachidesk/downloads/(Plugin)/(Manga) folder
Manga was downloaded as separate images
Opened 001.jpeg, it was not the first page that tachidesk displayed
Opened the manga on MangaSee and verified that 001.jpeg was indeed the correct first page.  Spot checked a few more pages to verify no issues there.
Verified that files were downloaded/had file times in order using --full-time
Arrived at ls -U, which does not sort the files in any way
Verified that the first five files that ls rattled off matched the first five pages that tachidesk displayed exactly

Seems like a file system/library gotcha.  Might not even show up depending on host platform/file system.  Not familiar with Java or what's in use, but probably just need an argument somewhere to sort the files (by name?) during the fetching process.

Hope all of that makes sense and makes tracking the issue down easier.

**Comment by CalebBarnes** [comment] 2023-05-25 21:07
I have the same issue. It is making the reader unusable. Also on Ubuntu server 20.

**Comment by Carpe-Diem-Postero** [comment] 2023-05-28 09:35
Any update about this bug?

**Comment by schroda** [comment] 2023-05-28 09:43
this should have been fixed in one of the preview versions, so try the latest one

**Comment by Carpe-Diem-Postero** [comment] 2023-05-28 09:52
> this should have been fixed in one of the preview versions, so try the latest one

Thanks, will do :)

**Comment by CalebBarnes** [comment] 2023-05-28 10:35
Just tested `ghcr.io/suwayomi/tachidesk:preview-alpine` and it looks like its fixed! Thanks.

**Comment by Syer10** [comment] 2023-08-05 20:13
This is fixed in the preview 👍

**Closed as completed by Syer10** 2023-08-05 20:13 UTC
Labels: bug
